DWAPlannerROS:
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  vx_samples: 10
  vtheta_samples: 20
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  sim_time: 2.0
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  forward_point_distance: 0.1
  stop_time_buffer: 0.2
